### ISSUE TITLE
How to deal with locally installed Node.js

### ISSUE THREAD

**Issue by karthilxg** [trecloux/yeoman-maven-plugin#19]
I have installed node and npm packages locally using the plugin https://github.com/eirslett/frontend-maven-plugin as part of my maven installation step, since the frontend-maven-plugin installed the node and npm packages locally under yo/node and yo/node-modules respectively, yeoman-maven-plugin  build goal fails while trying to run the node -version command because it is unable to find the node on the current working directory ${basedir}/yo/, I would like to know is there way we can ask the yeoman-maven-pluign to look the node under the given path. (An optional property for config)

**Comment by trecloux** [comment]
Hi @karthilxg 

Could you provide me the full commands you would need to type to run npm, bower and grunt ?
Do we need special parameters or only to change the binary path ?

**Comment by dachibro** [comment]
I am having the same problem in my Jenkins environment.  It works with the NodeJS plugin for some reason, but not with nvm.  

The NodeJS plugin has an option to supply the specified Node installation to the `$PATH`.  It must be doing something else behind the scenes, because nvm has a command that also appends the location of Node to the `$PATH` (`nvm use vx.x.x`).  

However, when Maven runs, it's not picking up Node.  I am using a shell script step before Maven executes. So, `$PATH` might be getting modified after that script runs. The more I think about it, I don't think it's an issue with your plugin.  

I am curious though.  Is there a way to explicitly pass the Node installation directory to Maven or your plugin?
